version: '3.3'
services:
  node:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - postgres
    environment:
      - PORT=4000
  postgres:
    build: ./database/ 
    ports:
      - 5433:5433
    env_file:
      - .env  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}   


